### ISSUE TITLE
'System' is undefined && Syntax Error system-polyfil.js - Internet Explorer 11 and Edge

### ISSUE THREAD

**Issue by tgienger** [ahmedshuhel/aurelia-meteor#3]
I tested angualr2-meteor as it uses System.js as well and did not get this error. If you need any other information/screenshots or whatever just let me know. Seems vague, but IE didn't really give me much else to work with.

I know when I click on the system-polyfil.js link provided in the console error, it takes me to the generated index.html rather than the actual system-polyfil.js file.

**Comment by ahmedshuhel** [comment]
The issue is fixed. Please install the latest version (0.2.0). We also renamed the package. https://atmospherejs.com/ahmedshuhel/aurelia 

Here is a [skeleton-navigation](http://github.com/aurelia/skeleton-navigation) [port](https://github.com/ahmedshuhel/aurelia-skeleton-meteor) deployed on [meteor](http://aurelia.meteor.com) . You can test it on IE.
